
services:
  projectr.backend:
    build:
      context: .
      dockerfile: src/Dockerfile

    container_name: projectr-api
    depends_on:
      db:
        condition: service_started
      seq:
        condition: service_started

    networks:
      - mynetwork

    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=projectr;Username=postgres;Password=password

      - Google__Android=${Google__Android}
      - Google__Ios=${Google__Ios}
      - Google__Web=${Google__Web}
      - Google__UseMock=${Google__UseMock}

      - WhatsApp__PhoneNumberId=${WhatsApp__PhoneNumberId}
      - WhatsApp__BaseUrl=${WhatsApp__BaseUrl}
      - WhatsApp__AccessToken=${WhatsApp__AccessToken}
      - WhatsApp__BusinessAccountId=${WhatsApp__BusinessAccountId}
      - WhatsApp__UseMock=${WhatsApp__UseMock}

      # - Cloudinary__CloudName=${Cloudinary__CloudName}
      # - Cloudinary__ApiKey=${Cloudinary__ApiKey}
      # - Cloudinary__ApiSecret=${Cloudinary__ApiSecret}

      # Serilog Seq config
      - Serilog__WriteTo__0__Name=Seq
      - Serilog__WriteTo__0__Args__serverUrl=http://seq:5341

    ports:
      - "5000:5000"
      - "5001:5001"
     
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Test@1234
    healthcheck:
      # test: ["CMD-SHELL", "timeout 5 bash -c '</dev/tcp/127.0.0.1/1433'"]
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -U sa -P 'Test@1234' -Q 'SELECT 1'"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 30s

    # ports:
    #   - "1433:1433"
    # volumes:
    #   - sqlserver_data:/var/opt/mssql
    # restart: always

    # ports:
    #   - "4400:80"
    #   - "5432:5432"
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    # healthcheck:
    #   test: [ "CMD-SHELL", "pg_isready -U postgres" ]
    #   interval: 10s
    #   retries: 5
    #   start_period: 30s
    #   timeout: 10s

    networks:
      - mynetwork

  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: always
    ports:
      - "5341:80" # UI accessible on http://localhost:5341
    volumes:
      - seq_data:/data
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=Test@1234   # optional: sets admin password on first run
    networks:
      - mynetwork

volumes:
  sqlserver_data:
  seq_data:

networks:
  mynetwork:
