using ProjectR.Backend.Shared;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace ProjectR.Backend.Application.Models
{
    public class OtpModel
    {
        [JsonIgnore]
        public Guid Id { get; set; }
        /// <summary>
        /// The actual OTP code generated by the system.
        /// </summary>
        [JsonIgnore]
        public string? Code { get; set; }
        /// <summary>
        /// This is a receipient option. For OTPs sent via SMS or Whatsapp, This can be null but the system will validate before proceeding
        /// </summary>
        public string? PhoneNumber { get; set; }
        /// <summary>
        /// The phone code of the destination if receiving via SMS or WhatsApp. e.g +234
        /// </summary>
        public string? CountryCode { get; set; }
        /// <summary>
        /// This is a receipient option. For OTPs sent via Email, This can be null but the system will validate before proceeding
        /// </summary>
        public string? Email { get; set; }
        [Required]
        public OtpType OtpType { get; set; }
        [JsonIgnore]
        public RecordStatus? RecordStatus { get; set; }
        [JsonIgnore]
        public DateTimeOffset CreatedAt { get; set; }
        [JsonIgnore]
        public DateTimeOffset ExpiryDate { get; set; }
        /// <summary>
        /// OTPs can be delivered via SMS, WhatsApp or Emails
        /// </summary>
        public DeliveryMode DeliveryMode { get; set; }
        public DateTimeOffset UpdatedAt { get; set; }
    }
}
