name: Docker Build and Deploy (Dev)

on:
  push:
    branches:
      - develop


env:
  DOCKERHUB_USERNAME: temilayon
  DOCKERHUB_PROJECT: temilayon/projectr.backend
  DOCKER_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Development

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: SSH into Host and Start Containers
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "Deploying on remote host..."
            cd /opt/ProjectR/build
            bash startsvcs.sh
