name: Docker Build and Deploy (Dev)
on:
  push:
    branches:
      - develop
env:
  DOCKERHUB_USERNAME: temilayon
  DOCKERHUB_PROJECT: temilayon/projectr.backend
  DOCKER_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Development

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up SSH with PEM file
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "Host *" > ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Run deployment script
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -tt sudo /opt/ProjectR/build/startsvcs.sh
